codeToName = {
    "AF" : "Afghanistan",
    "DZ" : "Algeria",
    "AO" : "Angola",
    "AR" : "Argentina",
    "AM" : "Armenia",
    "AU" : "Australia",
    "AZ" : "Azerbaijan",
    "AT" : "Austria",
    "BD" : "Bangladesh",
    "BY" : "Belarus",
    "BE" : "Belgium",
    "BT" : "Bhutan",
    "BW" : "Botswana",
    "BR" : "Brazil",
    "BG" : "Bulgaria",
    "KH" : "Cambodia",
    "CA" : "Canada",
    "CM" : "Cameroon",
    "CL" : "Chile",
    "CN" : "China",
    "CO" : "Colombia",
    "CD" : "Congo",
    "CR" : "Costa Rica",
    "HR" : "Croatia",
    "CZ" : "Czech Republic",
    "DK" : "Denmark",
    "EC" : "Ecuador",
    "EG" : "Egypt",
    "SV" : "El Salvador",
    "ET" : "Ethiopia",
    "FI" : "Finland",
    "FR" : "France",
    "GE" : "Georgia",
    "GH" : "Ghana",
    "DE" : "Germany",
    "GR" : "Greece",
    "GL" : "Green Land",
    "GT" : "Guatemala",
    "HK" : "Hong Kong",
    "HU" : "Hungary",
    "IS" : "Iceland",
    "IN" : "India",
    "ID" : "Indonesia",
    "IR" : "Iran",
    "IQ" : "Iraq",
    "IM" : "Isle of Man",
    "IE" : "Ireland",
    "IL" : "Israel",
    "IT" : "Italy",
    "JM" : "Jamaica",
    "JP" : "Japan",
    "JO" : "Jordan",
    "KZ" : "Kazaksthan",
    "KE" : "Kenya",
    "KP" : "North Korea",
    "KR" : "South Korea",
    "KW" : "Kuwait",
    "LB" : "Lebanon",
    "LY" : " Libya",
    "LT" : "Lithuania",
    "LU" : "Luxembourg",
    "MY" : "Malaysia",
    "MV" : "Maldives",
    "MU" : "Mauritius",
    "MX" : "Mexico",
    "MC" : "Monaco",
    "MN" : "Mongolia",
    "MA" : "Morocco",
    "MZ" : "Mozambique",
    "MM" : "Myanmar",
    "NA" : "Namibia",
    "NP" : "Nepal",
    "NL" : "Netherlands",
    "NZ" : "New Zealand",
    "NE" : "Niger",
    "NG" : "Nigeria",
    "NO" : "Norway",
    "OM" : "Oman",
    "PK" : "Pakistan",
    "PS" : "Palestine",
    "PA" : "Panama",
    "PY" : "Paraguay",
    "PG" : "Papa New Guinea",
    "PE" : "Peru",
    "PH" : "Philippines",
    "PL" : "Poland",
    "PT" : "Portugal",
    "QA" : "Qatar",
    "RO" : "Romania",
    "RU" : "Russian Federation",
    "RW" : "Rwanda",
    "SA" : "Saudi Arabia",
    "SN" : "Senegal",
    "RS" : "Serbia",
    "SC" : "Seychelles",
    "SG" : "Singapore",
    "ZA" : "South Africa",
    "SS" : "South Sudan",
    "ES" : "Spain",
    "LK" : "Sri Lanka",
    "SD" : "Sudan",
    "SE" : "Sweden",
    "CH" : "Switzerland",
    "SY" : "Syria",
    "TW" : "Taiwan",
    "TH" : "Thailand",
    "TR" : "Turkey",
    "UG" : "Uganda",
    "AE" : "United Arab Emirates",
    "GB" : "United Kingdom",
    "US" : "United States",
    "UY" : "Uruguay",
    "UZ" : "Uzbekistan",
    "VE" : "Venezuela",
    "VN" : "Vietnam",
    "YE" : "Yemen",
    "ZW" : "Zimbabwe"
 }

nameToCode = {
    "Afghanistan" : "AF",
    "Algeria" : "DZ",
    "Angola" : "AO",
    "Argentina" : "AR",
    "Armenia" : "AM",
    "Australia" : "AU",
    "Azerbaijan" : "AZ",
    "Austria" : "AT",
    "Bangladesh" : "BD",
    "Belarus" : "BY",
    "Belgium" : "BE",
    "Bhutan" : "BT",
    "Botswana" : "BW",
    "Brazil" : "BR",
    "Bulgaria" : "BG",
    "Cambodia" : "KH",
    "Canada" : "CA",
    "Cameroon" : "CM",
    "Chile" : "CL",
    "China" : "CN",
    "Colombia" : "CO",
    "Congo" : "CD",
    "Costa Rica" : "CR",
    "Croatia" : "HR",
    "Czech Republic" : "CZ",
    "Denmark" : "DK",
    "Ecuador" : "EC",
    "Egypt" : "EG",
    "El Salvador" : "SV",
    "Ethiopia" : "ET",
    "Finland" : "FI",
    "France" : "FR",
    "Georgia" : "GE",
    "Ghana" : "GH",
    "Germany" : "DE",
    "Greece" : "GR",
    "Green Land" : "GL",
    "Guatemala" : "GT",
    "Hong Kong" : "HK",
    "Hungary" : "HU",
    "Iceland" : "IS",
    "India" : "IN",
    "Indonesia" : "ID",
    "Iran" : "IR",
    "Iraq" : "IQ",
    "Isle of Man" : "IM",
    "Ireland" : "IE",
    "Israel" : "IL",
    "Italy" : "IT",
    "Jamaica" : "JM",
    "Japan" : "JP",
    "Jordan" : "JO",
    "Kazaksthan" : "KZ",
    "Kenya" : "KE",
    "North Korea" : "KP",
    "South Korea" : "KR",
    "Kuwait" : "KW",
    "Lebanon" : "LB",
    " Libya" : "LY",
    "Lithuania" : "LT",
    "Luxembourg" : "LU",
    "Malaysia" : "MY",
    "Maldives" : "MV",
    "Mauritius" : "MU",
    "Mexico" : "MX",
    "Monaco" : "MC",
    "Mongolia" : "MN",
    "Morocco" : "MA",
    "Mozambique" : "MZ",
    "Myanmar" : "MM",
    "Namibia" : "NA",
    "Nepal" : "NP",
    "Netherlands" : "NL",
    "New Zealand" : "NZ",
    "Niger" : "NE",
    "Nigeria" : "NG",
    "Norway" : "NO",
    "Oman" : "OM",
    "Pakistan" : "PK",
    "Palestine" : "PS",
    "Panama" : "PA",
    "Paraguay" : "PY",
    "Papa New Guinea" : "PG",
    "Peru" : "PE",
    "Philippines" : "PH",
    "Poland" : "PL",
    "Portugal" : "PT",
    "Qatar" : "QA",
    "Romania" : "RO",
    "Russian Federation" : "RU",
    "Rwanda" : "RW",
    "Saudi Arabia" : "SA",
    "Senegal" : "SN",
    "Serbia" : "RS",
    "Seychelles" : "SC",
    "Singapore" : "SG",
    "South Africa" : "ZA",
    "South Sudan" : "SS",
    "Spain" : "ES",
    "Sri Lanka" : "LK",
    "Sudan" : "SD",
    "Sweden" : "SE",
    "Switzerland" : "CH",
    "Syria" : "SY",
    "Taiwan" : "TW",
    "Thailand" : "TH",
    "Turkey" : "TR",
    "Uganda" : "UG",
    "United Arab Emirates" : "AE",
    "United Kingdom" : "GB",
    "United States" : "US",
    "Uruguay" : "UY",
    "Uzbekistan" : "UZ",
    "Venezuela" : "VE",
    "Vietnam" : "VN",
    "Yemen" : "YE",
    "Zimbabwe" : "ZW",
}
